### ISSUE TITLE
Implement Unix-like SIGHUP Reload for UiPath Config Settings

### ISSUE THREAD

**Issue by cprima** [rpapub/ProlificQuasar#2]
### Description

Implement a Unix-like SIGHUP reload mechanism in a UiPath project to dynamically reload configuration settings without stopping the running process. This feature will allow users to update configuration files and have the changes reflected in the workflow without restarting the UiPath robot.

### Acceptance Criteria

- [ ] The robot can detect a signal for changes to the configuration file without requiring a job restart.
- [ ] The robot reloads configuration settings when triggered by an asset.
- [ ] No interruption or downtime in the robot’s task execution during the reload process.

### Subtasks

- [ ] Implement asset for configuration changes.
- [ ] Develop logic to reload the configuration dynamically.
- [ ] Create a test case to verify correct behavior on config reload.
- [ ] Write documentation
- [ ] write publications

### Related Issues / Dependencies

- Related to: tbd
- Depends on: tbd
